  File "/home/ubuntu/margin/git_auto_push.py", line 7
    return process.stdout
IndentationError: unexpected indent
An error occurred while pushing changes: fatal: not a git repository (or any of the parent directories): .git

Changes pushed successfully on 2023-11-11.
An error occurred while pushing changes: 
An error occurred while pushing changes: To github.com:sk18sept/margin.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'github.com:sk18sept/margin.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

An error occurred while pushing changes: To github.com:sk18sept/margin.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'github.com:sk18sept/margin.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

An error occurred while pushing changes: 
Changes pushed successfully on 2023-11-16.
Changes pushed successfully on 2023-11-17.
Changes pushed successfully on 2023-11-18.
